---

#-----------------------------------------------------------------------------------------------------------------------
# Resource Types
#-----------------------------------------------------------------------------------------------------------------------
resource_types:

- name: github-release
  type: docker-image
  source:
    repository: quay.io/hellofresh/gh-status-dynamic

#-----------------------------------------------------------------------------------------------------------------------
# Resources
#-----------------------------------------------------------------------------------------------------------------------
resources:

- name: source-code
  type: git
  source:
    uri: {{github_repository_uri}}
    branch: master

- name: release-candidate
  type: github-release
  source:
    user: {{github_organization}}
    repository: {{github_repository}}
    access_token: {{github_access_token}}
    pre_release: true

- name: release
  type: github-release
  source:
    user: {{github_organization}}
    repository: {{github_repository}}
    access_token: {{github_access_token}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.0-rc.1
    uri: {{github_repository_uri}}
    branch: version
    file: version

#-----------------------------------------------------------------------------------------------------------------------
# Groups
#-----------------------------------------------------------------------------------------------------------------------
groups:

- name: pre-release
  jobs:
  - run-unit-tests
  - create-release-candidate

- name: release
  jobs:
  - create-release

#-----------------------------------------------------------------------------------------------------------------------
# Jobs
#-----------------------------------------------------------------------------------------------------------------------
jobs:

- name: run-unit-tests
  serial: true
  plan:

  # Trigger unit tests when the source code is updated
  - get: source-code
    trigger: true

  # Run unit tests
  - task: unit-tests
    file: source-code/ci/tasks/run-unit-tests.yml
    params:
      PROJECT_SRC: {{project_src}}

# Create Release Candidate
#-----------------------------------------------------------------------------------------------------------------------
- name: create-release-candidate
  public: false
  serial: true
  plan:

  # Trigger build on master update
  - get: source-code
    trigger: true
    passed: [run-unit-tests]

  # Create a release artifact
  - task: create-artifact
    file: source-code/ci/tasks/create-artifact.yml
    params:
      PROJECT_SRC: {{project_src}}

  # Bump the rc version
  - put: version
    params:
      pre: 'rc'

  # Upload a release candidate to GitHub
  - put: release-candidate
    params:
      name: version/version
      tag: version/version
      globs:
      - artifacts/*.tar.gz

# Create Release
#-----------------------------------------------------------------------------------------------------------------------
- name: create-release
  serial: true
  plan:

  # Get the latest release candidate
  - get: release-candidate

  # Bump the version of the release
  - put: version
    params:
      bump: final

  # Upload a release to Github
  - put: release
    params:
      name: version/version
      tag: version/version
      globs:
      - release-candidate/*.tar.gz
