---

#-----------------------------------------------------------------------------------------------------------------------
# Resource Types
#-----------------------------------------------------------------------------------------------------------------------
resource_types:

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

#-----------------------------------------------------------------------------------------------------------------------
# Resources
#-----------------------------------------------------------------------------------------------------------------------
resources:

- name: source-code
  type: pull-request
  source:
    uri: {{github_repository_uri}}
    repo: {{github_pr_repository}}
    access_token: {{github_access_token}}

#-----------------------------------------------------------------------------------------------------------------------
# Jobs
#-----------------------------------------------------------------------------------------------------------------------
jobs:

- name: run-unit-tests
  public: false
  serial: true
  plan:

  # Trigger unit tests when a PR is submitted
  - get: source-code
    trigger: true

  # Set the unit test github status for this PR to pending
  - put: source-code
    params:
      path: source-code
      context: unit-tests
      status: pending

  # Run unit tests
  - task: unit-tests
    file: source-code/ci/tasks/run-unit-tests.yml
    params:
        PROJECT_SRC: {{project_src}}

    # If successful, set the unit test github status for this PR to success
    on_success:
      put: source-code
      params:
        path: source-code
        context: unit-tests
        status: success

    # If unsuccessful, set the unit test github status for this PR to unsuccessful
    on_failure:
      put: source-code
      params:
        path: source-code
        context: unit-tests
        status: failure
