language: go

go:
  - "1.10"
  - "stable"

install:
  - mkdir -p $GOPATH/bin
  - make deps

script:
  - make test

before_deploy:
  - make

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: dist/phanes*
    skip_cleanup: true
    file_glob: true
    on:
      repo: hellofresh/phanes
      tags: true
