---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1"

inputs:
  - name: source-code

outputs:
  - name: artifacts

run:
  path: source-code/ci/scripts/create-artifact.sh
